<!DOCTYPE html>
<html>
   <head>
      <title>flake8 violations: env/lib/python3.9/site-packages/django/db/models/base.py</title>
      <meta http-equiv="Content-Type" value="text/html; charset=UTF-8">
      <link rel="stylesheet" href="styles.css">
<script>
function bindHandler(link) {
   var code = link.getAttribute('data-code');
   var key = location.pathname + '#' + code;

   var ul = link.parentNode.querySelector('.details');
   if (sessionStorage[key] != 'open') {
      ul.style.display = 'none';
   }
   link.addEventListener('click', function (event) {
      if (!ul.style.display || ul.style.display == 'none') {
         ul.style.display = 'block';
         sessionStorage[key] = 'open';
      } else {
         ul.style.display = 'none';
         sessionStorage[key] = 'closed';
      }
   });
}

window.addEventListener('DOMContentLoaded', function () {
   var links = document.querySelectorAll('#index > li > a');
   for (var i = 0; i < links.length; i++) {
      bindHandler(links[i]);
   }
});
</script>
   </head>
   <body>
      <div id="masthead" class="sev-3"></div>
      <div id="page">
         <p id="srclink">
            <a title="View full annotated source"
               href="env.lib.python3.9.site-packages.django.db.models.base.source.html">
               <img src="file.svg" alt="&#x2261;">
            </a></p>
         <h1>
            <a href="index.html">
               <img src="back.svg" alt="&#x2B05;">
               env/lib/python3.9/site-packages/django/db/models/base.py
            </a>
         </h1>

         <ul id="index">
         
         <li>
            <a data-code="I101">
               <span class="count sev-3">
                  2
               </span>
               <strong>I101:</strong> Imported names are in the wrong order. Should be FieldDoesNotExist, FieldError, MultipleObjectsReturned, NON_FIELD_ERRORS, ObjectDoesNotExist, ValidationError
               
                  (and 1 similar)
               
            </a>
            <ul class="details">
            <li>
               
               <p>Imported names are in the wrong order. Should be FieldDoesNotExist, FieldError, MultipleObjectsReturned, NON_FIELD_ERRORS, ObjectDoesNotExist, ValidationError:</p>
               
               <a href="env.lib.python3.9.site-packages.django.db.models.base.source.html#l11">
                  <tt><i>11</i> <span class="kn">from</span> <span class="nn">django.core.exceptions</span> <span class="kn">import</span> <span class="p">(</span></tt>
               </a>
            </li><li>
               
               <p>Imported names are in the wrong order. Should be ExpressionWrapper, IntegerField, Max, NOT_PROVIDED, Value:</p>
               
               <a href="env.lib.python3.9.site-packages.django.db.models.base.source.html#l19">
                  <tt><i>19</i> <span class="kn">from</span> <span class="nn">django.db.models</span> <span class="kn">import</span> <span class="p">(</span></tt>
               </a>
            </li>
            </ul>
         </li>
         
         </ul>
      </div>
   </body>
</html>