<!DOCTYPE html>
<html>
   <head>
      <title>flake8 violations: env/lib/python3.9/site-packages/pip/_internal/utils/direct_url_helpers.py</title>
      <meta http-equiv="Content-Type" value="text/html; charset=UTF-8">
      <link rel="stylesheet" href="styles.css">
<script>
function bindHandler(link) {
   var code = link.getAttribute('data-code');
   var key = location.pathname + '#' + code;

   var ul = link.parentNode.querySelector('.details');
   if (sessionStorage[key] != 'open') {
      ul.style.display = 'none';
   }
   link.addEventListener('click', function (event) {
      if (!ul.style.display || ul.style.display == 'none') {
         ul.style.display = 'block';
         sessionStorage[key] = 'open';
      } else {
         ul.style.display = 'none';
         sessionStorage[key] = 'closed';
      }
   });
}

window.addEventListener('DOMContentLoaded', function () {
   var links = document.querySelectorAll('#index > li > a');
   for (var i = 0; i < links.length; i++) {
      bindHandler(links[i]);
   }
});
</script>
   </head>
   <body>
      <div id="masthead" class="sev-3"></div>
      <div id="page">
         <p id="srclink">
            <a title="View full annotated source"
               href="env.lib.python3.9.site-packages.pip._internal.utils.direct_url_helpers.source.html">
               <img src="file.svg" alt="&#x2261;">
            </a></p>
         <h1>
            <a href="index.html">
               <img src="back.svg" alt="&#x2B05;">
               env/lib/python3.9/site-packages/pip/_internal/utils/direct_url_helpers.py
            </a>
         </h1>

         <ul id="index">
         
         <li>
            <a data-code="A001">
               <span class="count sev-3">
                  2
               </span>
               <strong>A001:</strong> variable "hash" is shadowing a python builtin
               
            </a>
            <ul class="details">
            <li>
               
               <a href="env.lib.python3.9.site-packages.pip._internal.utils.direct_url_helpers.source.html#l93">
                  <tt><i>93</i>         <span class="nb">hash</span> <span class="o">=</span> <span class="kc">None</span></tt>
               </a>
            </li><li>
               
               <a href="env.lib.python3.9.site-packages.pip._internal.utils.direct_url_helpers.source.html#l96">
                  <tt><i>96</i>             <span class="nb">hash</span> <span class="o">=</span> <span class="s2">&quot;</span><span class="si">{}</span><span class="s2">=</span><span class="si">{}</span><span class="s2">&quot;</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">hash_name</span><span class="p">,</span> <span class="n">link</span><span class="o">.</span><span class="n">hash</span><span class="p">)</span></tt>
               </a>
            </li>
            </ul>
         </li>
         
         <li>
            <a data-code="I101">
               <span class="count sev-3">
                  1
               </span>
               <strong>I101:</strong> Imported names are in the wrong order. Should be ArchiveInfo, DIRECT_URL_METADATA_NAME, DirInfo, DirectUrl, DirectUrlValidationError, VcsInfo
               
            </a>
            <ul class="details">
            <li>
               
               <a href="env.lib.python3.9.site-packages.pip._internal.utils.direct_url_helpers.source.html#l3">
                  <tt><i>3</i> <span class="kn">from</span> <span class="nn">pip._internal.models.direct_url</span> <span class="kn">import</span> <span class="p">(</span></tt>
               </a>
            </li>
            </ul>
         </li>
         
         </ul>
      </div>
   </body>
</html>